### ISSUE TITLE
Need Sample OST for testing

### ISSUE THREAD

**Issue by JeetDSharma** [Switchdoctorstu/OSTPSTExtractor#1]
Could you upload a sample.ost file for testing the code

**Comment by Switchdoctorstu** [comment]
I only have my personal OST files so i'm reluctant to upload. They're created by outlook and usually sit in
drive:\Users\user\AppData\Local\Microsoft\Outlook
Outlook used to use PST files (I THINK my code will read these too) but now seems to write OST files to the local machine instead.
